### ISSUE TITLE
Chat Display not counting

### ISSUE THREAD

**Issue by Diasaur** [MenesesPT/TimerVTT#10]
?At least for me? For a while now the chat message doesn't count down anymore. The Timer otherwise works as usual (can create them via macro and when over it rings and sends the EndMessage and stuff) but it is sometimes really weird not knowing how much longer the players have for a task (or to track it separately or to have to roughly count backwards from how old the message is).

**Comment by MenesesPT** [comment]
Which foundry version are you running it on?

**Comment by Diasaur** [comment]
On version 11 build 307.
But it has been not ticking down in chat for a while (at least including version 10).

**Comment by MenesesPT** [comment]
I faced the same issue when trying one of the new versions of foundry and had made some changes to the package locally but never commited them. 
They have now been merged, so the messages in chat should update! I haven't had oportunity to test everything right now but it should work 🤞

**Comment by Diasaur** [comment]
Works like a charm in v 11 b 307! Thank you very much!
