### ISSUE TITLE
old flat core compatibility

### ISSUE THREAD

**Issue by vaka42** [MenesesPT/TimerVTT#11]
"The module "timer" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object"

Im using Foundry Version 11 Stable - Build 315. 

![grafik](https://github.com/MenesesPT/TimerVTT/assets/23260825/cfaebf3e-e037-4a7c-82b9-c531f947258e)

**Comment by MenesesPT** [comment]
Fixed on v0.2.6
