### ISSUE TITLE
End Message on a Private timer cannot be set to private

### ISSUE THREAD

**Issue by DariusWolfe** [MenesesPT/TimerVTT#5]
I want to be able to use this to remind myself of things without necessarily showing it to the player, but right now, the End chat message is public to all, and there doesn't appear to be a way to fix that. I've been just omitting the message, but sometimes I miss the alarm sound in the midst of busy chat, so the end chat message would be useful.

**Comment by MenesesPT** [comment]
When the timer is private it should no longer send the message to everyone.
Thanks!
