### ISSUE TITLE
Toggle to keep timer running while game is paused

### ISSUE THREAD

**Issue by calexus1986** [MenesesPT/TimerVTT#6]
I'd like to use this for my gaming groups breaks, conversations can spin a 5 minute break into an hour quite easily and it's nice to set aside a time for talking so everyone knows when the time is up the game is going, any chance of putting a toggle in the creation that would keep the timer going when the game is paused

**Comment by MenesesPT** [comment]
I've done a small update that implements your request. (52bd0017d8dfca7e865403ccfa25fdc3f8204360)

Thank you for your suggestion!
