### ISSUE TITLE
Have a private timer, but the sound still emits to players

### ISSUE THREAD

**Issue by wilkinsalex** [MenesesPT/TimerVTT#7]
I would like to have the timer be "private" so they cannot see how long the timer is lasting for but I still want them to be able to hear the sound. Is this possible? I tried various options and as soon as I enable "Private Timer" its only for the GM. 

The use case would be to add a "ticking noise" for them to make a decision etc. but not tell them how long they have =)

**Comment by MenesesPT** [comment]
Currently the private timer option hides everything from other players, but I like your idea!
I will implement it this week!

**Comment by MenesesPT** [comment]
I've implemented your request, I believe it will cause a little panic among the players since they don't know how much time they have left.

**Comment by wilkinsalex** [comment]
........ Excellent hahaha

**Comment by wilkinsalex** [comment]
***Narrator Voice*** It did indeed cause panic... and it was wonderful thanks so much!
